"""Add refresh_tokens

Revision ID: ad9dba31b12a
Revises: 
Create Date: 2026-02-26 11:19:03.991389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad9dba31b12a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_email', sa.String(length=150), nullable=False),
    sa.Column('college_id_number', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('college_email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('driver_verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'verified', 'rejected', name='verificationstatusenum'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_table('face_data',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('face_embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('last_verified_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('identity_verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_id_number', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'verified', 'rejected', name='verificationstatusenum'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('saved_addresses',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )

    op.add_column('ride_participants', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('ride_participants', sa.Column('pickup_lng', sa.Float(), nullable=True))
    op.add_column('ride_participants', sa.Column('pickup_address', sa.String(), nullable=True))
    op.add_column('ride_participants', sa.Column('pickup_otp', sa.String(length=4), nullable=True))
    op.add_column('ride_participants', sa.Column('is_picked_up', sa.Boolean(), nullable=False))
    op.add_column('ride_requests', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('ride_requests', sa.Column('pickup_lng', sa.Float(), nullable=True))
    op.add_column('ride_requests', sa.Column('pickup_address', sa.String(), nullable=True))
    op.add_column('rides', sa.Column('pickup_otp', sa.String(length=4), nullable=True))
    op.alter_column('users', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_driver_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_driver_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('rides', 'pickup_otp')
    op.drop_column('ride_requests', 'pickup_address')
    op.drop_column('ride_requests', 'pickup_lng')
    op.drop_column('ride_requests', 'pickup_lat')
    op.drop_column('ride_participants', 'is_picked_up')
    op.drop_column('ride_participants', 'pickup_otp')
    op.drop_column('ride_participants', 'pickup_address')
    op.drop_column('ride_participants', 'pickup_lng')
    op.drop_column('ride_participants', 'pickup_lat')

    op.drop_table('saved_addresses')
    op.drop_table('refresh_tokens')
    op.drop_table('identity_verifications')
    op.drop_table('face_data')
    op.drop_table('driver_verifications')
    op.drop_table('college_students')
    # ### end Alembic commands ###
